# Generated by Django 4.2 on 2023-05-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
