# Generated by Django 4.2 on 2023-05-08 15:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
